#! /bin/bash
echo -e "What is the name of the item? --> \c"
read ITEM
echo -e "What is the item cost? --> \c"
read COST
echo -e "What is the selling price of the item? --> \c"
read PRICE
echo -e "How much of the item is in inventory? --> \c"
read INV

echo -e "$ITEM \t $COST \t $PRICE \t $INV" >> ~/hardware.database

sort ~/hardware.database > /tmp/$$.tmp
rm ~/hardware.database
mv /tmp/$$.tmp ~/hardware.database
